# Generated by Django 2.1.4 on 2019-01-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propsmessage',
            old_name='user_from',
            new_name='teammate_from',
        ),
        migrations.RenameField(
            model_name='propsmessage',
            old_name='user_to',
            new_name='teammate_to',
        ),
    ]
