# Generated by Django 2.1.5 on 2019-01-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190103_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
