# Generated by Django 2.1.5 on 2019-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_teammate_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
