# Generated by Django 2.1.5 on 2019-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190105_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propsmessage',
            name='teammate_to',
        ),
        migrations.AddField(
            model_name='propsmessage',
            name='teammates_to',
            field=models.ManyToManyField(to='people.Teammate'),
        ),
    ]
