# Generated by Django 2.1.5 on 2019-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190105_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propsmessage',
            name='teammates_to',
            field=models.ManyToManyField(related_name='receivers', to='people.Teammate'),
        ),
    ]
