# Generated by Django 2.1.5 on 2019-01-05 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190105_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='propsmessage',
            name='sent_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
