# Generated by Django 2.1.5 on 2019-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_propsmessage_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='propsmessage',
            name='identifying_ts',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
