# Generated by Django 2.1.5 on 2019-01-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_propsmessage_identifying_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propsmessage',
            name='teammate_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='props_given', to='people.Teammate'),
        ),
        migrations.AlterField(
            model_name='propsmessage',
            name='teammates_to',
            field=models.ManyToManyField(related_name='props_gotten', to='people.Teammate'),
        ),
    ]
