# Generated by Django 2.1.5 on 2019-01-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190105_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
