# Generated by Django 2.1.5 on 2019-01-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_teammate_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammate',
            name='birthday',
        ),
        migrations.AddField(
            model_name='teammate',
            name='bday_day',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammate',
            name='bday_month',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
