# Generated by Django 2.1.5 on 2019-01-10 23:11

from django.db import migrations

import mptt
import mptt.managers


def rebuild_tm_mptt(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    Teammate = apps.get_model("people", "Teammate")
    manager.model = Teammate
    mptt.register(Teammate, order_insertion_by=["name"], parent_attr="manager")
    manager.contribute_to_class(Teammate, "objects")
    manager.rebuild()


def backwards_no_op(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [("people", "0016_auto_20190110_1447")]

    operations = [migrations.RunPython(rebuild_tm_mptt, backwards_no_op)]
