# Generated by Django 2.1.5 on 2019-01-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_teammate_okrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('purpose', models.TextField(blank=True)),
                ('details_url', models.URLField(blank=True)),
                ('contact_block', models.TextField(blank=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('members', models.ManyToManyField(limit_choices_to={'is_hidden': False}, to='people.Teammate')),
            ],
        ),
    ]
