# Generated by Django 2.1.5 on 2019-01-29 06:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20190128_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='people.Team'),
        ),
    ]
