# Generated by Django 2.1.5 on 2019-01-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20190128_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
