# Generated by Django 2.1.5 on 2019-01-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20190129_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='people.Team')),
            ],
        ),
    ]
