# Generated by Django 2.1.5 on 2019-01-30 05:43

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_teammetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='manager',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_reports', to='people.Teammate'),
        ),
    ]
